DATABASE_URL = "postgresql://neondb_owner:gw0U8hvZePRS@ep-divine-block-a5z8w0ly.us-east-2.aws.neon.tech/neondb?sslmode=require"
OPENAI_API_KEY = "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"
TAVILY_API_KEY = "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"
